var array = argument0;
switch (array_length_1d(array)) {
	case 1:     return script_execute( fp_get_val(array[0]) ); break;
    case 2:     return script_execute( fp_get_val(array[0]), fp_get_val(array[1]) ); break;
    case 3:     return script_execute( fp_get_val(array[0]), fp_get_val(array[1]), fp_get_val(array[2]) ); break;
    case 4:     return script_execute( fp_get_val(array[0]), fp_get_val(array[1]), fp_get_val(array[2]), fp_get_val(array[3]) ); break;
    case 5:     return script_execute( fp_get_val(array[0]), fp_get_val(array[1]), fp_get_val(array[2]), fp_get_val(array[3]), fp_get_val(array[4]) ); break;
    case 6:     return script_execute( fp_get_val(array[0]), fp_get_val(array[1]), fp_get_val(array[2]), fp_get_val(array[3]), fp_get_val(array[4]), fp_get_val(array[5]) ); break;
    case 7:     return script_execute( fp_get_val(array[0]), fp_get_val(array[1]), fp_get_val(array[2]), fp_get_val(array[3]), fp_get_val(array[4]), fp_get_val(array[5]), fp_get_val(array[6]) ); break;
    case 8:     return script_execute( fp_get_val(array[0]), fp_get_val(array[1]), fp_get_val(array[2]), fp_get_val(array[3]), fp_get_val(array[4]), fp_get_val(array[5]), fp_get_val(array[6]), fp_get_val(array[7]) ); break;
    case 9:     return script_execute( fp_get_val(array[0]), fp_get_val(array[1]), fp_get_val(array[2]), fp_get_val(array[3]), fp_get_val(array[4]), fp_get_val(array[5]), fp_get_val(array[6]), fp_get_val(array[7]), fp_get_val(array[8]) ); break;
    case 10:    return script_execute( fp_get_val(array[0]), fp_get_val(array[1]), fp_get_val(array[2]), fp_get_val(array[3]), fp_get_val(array[4]), fp_get_val(array[5]), fp_get_val(array[6]), fp_get_val(array[7]), fp_get_val(array[8]), fp_get_val(array[9]) ); break;
    case 11:    return script_execute( fp_get_val(array[0]), fp_get_val(array[1]), fp_get_val(array[2]), fp_get_val(array[3]), fp_get_val(array[4]), fp_get_val(array[5]), fp_get_val(array[6]), fp_get_val(array[7]), fp_get_val(array[8]), fp_get_val(array[9]), fp_get_val(array[10]) ); break;
    case 12:    return script_execute( fp_get_val(array[0]), fp_get_val(array[1]), fp_get_val(array[2]), fp_get_val(array[3]), fp_get_val(array[4]), fp_get_val(array[5]), fp_get_val(array[6]), fp_get_val(array[7]), fp_get_val(array[8]), fp_get_val(array[9]), fp_get_val(array[10]), fp_get_val(array[11]) ); break;
    case 13:    return script_execute( fp_get_val(array[0]), fp_get_val(array[1]), fp_get_val(array[2]), fp_get_val(array[3]), fp_get_val(array[4]), fp_get_val(array[5]), fp_get_val(array[6]), fp_get_val(array[7]), fp_get_val(array[8]), fp_get_val(array[9]), fp_get_val(array[10]), fp_get_val(array[11]), fp_get_val(array[12]) ); break;
    case 14:    return script_execute( fp_get_val(array[0]), fp_get_val(array[1]), fp_get_val(array[2]), fp_get_val(array[3]), fp_get_val(array[4]), fp_get_val(array[5]), fp_get_val(array[6]), fp_get_val(array[7]), fp_get_val(array[8]), fp_get_val(array[9]), fp_get_val(array[10]), fp_get_val(array[11]), fp_get_val(array[12]), fp_get_val(array[13]) ); break;
    case 15:    return script_execute( fp_get_val(array[0]), fp_get_val(array[1]), fp_get_val(array[2]), fp_get_val(array[3]), fp_get_val(array[4]), fp_get_val(array[5]), fp_get_val(array[6]), fp_get_val(array[7]), fp_get_val(array[8]), fp_get_val(array[9]), fp_get_val(array[10]), fp_get_val(array[11]), fp_get_val(array[12]), fp_get_val(array[13]), fp_get_val(array[14]) ); break;
    case 16:    return script_execute( fp_get_val(array[0]), fp_get_val(array[1]), fp_get_val(array[2]), fp_get_val(array[3]), fp_get_val(array[4]), fp_get_val(array[5]), fp_get_val(array[6]), fp_get_val(array[7]), fp_get_val(array[8]), fp_get_val(array[9]), fp_get_val(array[10]), fp_get_val(array[11]), fp_get_val(array[12]), fp_get_val(array[13]), fp_get_val(array[14]), fp_get_val(array[15]) ); break;
    case 17:    return script_execute( fp_get_val(array[0]), fp_get_val(array[1]), fp_get_val(array[2]), fp_get_val(array[3]), fp_get_val(array[4]), fp_get_val(array[5]), fp_get_val(array[6]), fp_get_val(array[7]), fp_get_val(array[8]), fp_get_val(array[9]), fp_get_val(array[10]), fp_get_val(array[11]), fp_get_val(array[12]), fp_get_val(array[13]), fp_get_val(array[14]), fp_get_val(array[15]), fp_get_val(array[16]) ); break;
    case 18:    return script_execute( fp_get_val(array[0]), fp_get_val(array[1]), fp_get_val(array[2]), fp_get_val(array[3]), fp_get_val(array[4]), fp_get_val(array[5]), fp_get_val(array[6]), fp_get_val(array[7]), fp_get_val(array[8]), fp_get_val(array[9]), fp_get_val(array[10]), fp_get_val(array[11]), fp_get_val(array[12]), fp_get_val(array[13]), fp_get_val(array[14]), fp_get_val(array[15]), fp_get_val(array[16]), fp_get_val(array[17]) ); break;
    case 19:    return script_execute( fp_get_val(array[0]), fp_get_val(array[1]), fp_get_val(array[2]), fp_get_val(array[3]), fp_get_val(array[4]), fp_get_val(array[5]), fp_get_val(array[6]), fp_get_val(array[7]), fp_get_val(array[8]), fp_get_val(array[9]), fp_get_val(array[10]), fp_get_val(array[11]), fp_get_val(array[12]), fp_get_val(array[13]), fp_get_val(array[14]), fp_get_val(array[15]), fp_get_val(array[16]), fp_get_val(array[17]), fp_get_val(array[18]) ); break;
    case 20:    return script_execute( fp_get_val(array[0]), fp_get_val(array[1]), fp_get_val(array[2]), fp_get_val(array[3]), fp_get_val(array[4]), fp_get_val(array[5]), fp_get_val(array[6]), fp_get_val(array[7]), fp_get_val(array[8]), fp_get_val(array[9]), fp_get_val(array[10]), fp_get_val(array[11]), fp_get_val(array[12]), fp_get_val(array[13]), fp_get_val(array[14]), fp_get_val(array[15]), fp_get_val(array[16]), fp_get_val(array[17]), fp_get_val(array[18]), fp_get_val(array[19]) ); break;
}
