list = argument0;
script_execute( list[| 0], 
				list[| 1], 
				list[| 2], 
				list[| 3], 
				list[| 4], 
				list[| 5], 
				list[| 6], 
				list[| 7], 
				list[| 8], 
				list[| 9], 
				list[| 10], 
				list[| 11], 
				list[| 12], 
				list[| 13], 
				list[| 14], 
				list[| 15], 
				list[| 16], 
				list[| 17], 
				list[| 18], 
				list[| 19], 
				list[| 20] 
)